/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lujah
 */
public class FrmMenu extends javax.swing.JFrame {
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        MenuInstructor = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenuItem();
        MenuMembresia = new javax.swing.JMenuItem();
        MenuRegistros = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu4.setText("Administrador");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        MenuInstructor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuInstructor.setText("⍟ Registro Instructores");
        MenuInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInstructorActionPerformed(evt);
            }
        });
        jMenu4.add(MenuInstructor);

        MenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuClientes.setText("⍟ Registro Clientes");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });
        jMenu4.add(MenuClientes);

        MenuMembresia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuMembresia.setText("⍟ Registro Membresías");
        MenuMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMembresiaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuMembresia);

        MenuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuRegistros.setText("⍟ Ver Registros");
        MenuRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrosActionPerformed(evt);
            }
        });
        jMenu4.add(MenuRegistros);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Iniciar");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInstructorActionPerformed
        FrmInstructores Frm = new FrmInstructores();
        Frm.setVisible(true);
    }//GEN-LAST:event_MenuInstructorActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        FrmClientes Frm = new FrmClientes();
        Frm.setVisible(true);
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void MenuMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMembresiaActionPerformed
        FrmMembresias Frm = new FrmMembresias();
        Frm.setVisible(true);
    }//GEN-LAST:event_MenuMembresiaActionPerformed

    private void MenuRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrosActionPerformed
        FrmRegistros Frm = new FrmRegistros();
        Frm.setVisible(true);
    }//GEN-LAST:event_MenuRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuInstructor;
    private javax.swing.JMenuItem MenuMembresia;
    private javax.swing.JMenuItem MenuRegistros;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
